version: '2'

volumes:
    logs:
        driver: local

services:
    interview:
        container_name: interview-php
        build:
             context: ./
             dockerfile: DockerfilePHP
        working_dir: /var/www/html
        command: php -S 0.0.0.0:8081 -t public
        environment:
            docker: "true"
        ports:
            - 8081:8081
        volumes:
            - .:/var/www/html
            - logs:/var/www/html/logs
        links:
            - db
    db:
        container_name: interview-mysql
        build:
             context: ./
             dockerfile: DockerfileMysql
        ports:
            - 3036:3036
        volumes:
            - /home/unify/data/dockermysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root@123
            MYSQL_USER: rlabh
            MYSQL_PASSWORD: rlabh@123
            MYSQL_DATABASE: slimapp
